In [1]:
import numpy as np

# Numpy is Numerical Python.

In [9]:
aaray2 = np.array([[7,8,9],[5,6,3]])

In [11]:
aaray2

array([[7, 8, 9],
       [5, 6, 3]])

In [12]:
# np.zeros
array2 = np.zeros([7,8] , dtype=int) 

In [13]:
dtype = array2

In [14]:
print(dtype)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [15]:
# np.arange
array8 = np.arange(12,80,5)

In [18]:
array8

array([12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77])

7

#linspace
# to get the number of evenly spaced values between intervals


In [19]:
array5 = np.linspace(12,75,7)

In [20]:
array5

array([12. , 22.5, 33. , 43.5, 54. , 64.5, 75. ])

In [23]:
array7 = np.full([12,9,2],7)

In [24]:
array7

array([[[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 7],
        [7, 

identity matrix

In [25]:
array8 = np.identity(5)

In [26]:
array8

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#converting list into array


In [27]:
list_ = [9,5,4]
array9 = np.asarray(list_)

In [28]:
array9

array([9, 5, 4])

In [35]:
p = np.random.randint(2,7,[2,4])

In [36]:
p

array([[3, 2, 3, 2],
       [4, 5, 5, 5]])

In [37]:
q = np.random.randint(6,14,(2,4))

In [38]:
q

array([[ 8,  7,  9, 13],
       [13,  7, 11, 10]])

In [40]:
r = np.multiply(p,q)

In [41]:
print(r)

[[24 14 27 26]
 [52 35 55 50]]


In [42]:
s = np.divide(p,q)

In [43]:
s

array([[0.375     , 0.28571429, 0.33333333, 0.15384615],
       [0.30769231, 0.71428571, 0.45454545, 0.5       ]])

In [45]:
z = np.divide(10,2)

In [46]:
z

5.0

In [48]:
# multiplication
multiply = np.multiply(350, 286)

In [49]:
print(multiply)

100100


In [50]:
x= np.random.randint(2,12,[2,4])

In [51]:
x

array([[3, 2, 6, 5],
       [8, 3, 9, 4]])

aggritate function

In [60]:
s = np.random.randint(2,13,[3,4])
print(s)

[[ 7 10 10 11]
 [12 12  6  5]
 [ 8  4  6 12]]


In [72]:
total_sum = np.sum(s)

In [73]:
print(total_sum)

103


In [71]:
print(np.sum(s))

103


In [65]:
print(s)

[[ 7 10 10 11]
 [12 12  6  5]
 [ 8  4  6 12]]


In [76]:
maximum = s.max()

In [77]:
print(maximum)

12


In [78]:
s.min()

4

transpose

In [79]:
array10 = np.random.randint(3,15,[5,7])

transpose = np.transpose(array10)

In [81]:
print(array10)

[[10 11 11 13 13  8 10]
 [13  6  4 12 10 12  6]
 [14  7 14 12  8  9  5]
 [ 9  8 10 12 13 12 12]
 [12 12  5  9 10 12 10]]


In [80]:
print(transpose)

[[10 13 14  9 12]
 [11  6  7  8 12]
 [11  4 14 10  5]
 [13 12 12 12  9]
 [13 10  8 13 10]
 [ 8 12  9 12 12]
 [10  6  5 12 10]]


In [ ]:
array_4 = np.array([[1,2,3],[4,5,6]])
print(f"The total number of elements in array_4 =  {array_4.size}")
The total number of elements in array_4 =  6

In [82]:
array_8 = np.array([[1,2,3],[4,5,6]])

In [83]:
print(array_8)

[[1 2 3]
 [4 5 6]]


In [84]:
n = array_8.size

In [85]:
print(n)

6


In [87]:
print(array_8.size)

6
